<?php 
	$title = 'Agrega los datos de tu mascota';
	$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

	$form->setAttribute('action', $this->url('post', ['action' => 'add']));
	$form->prepare();
?>

<?php
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
?>

<?php
	echo $this->formRow($form->get('nombre'));
?>
<br/>
<br/>
<?php
	echo $this->formRow($form->get('raza'));
?>
<br/>
<br/>
<?php
	echo $this->formRow($form->get('sexo'));
?>
<br/>
<br/>
<?php
	echo $this->formRow($form->get('caracteristicas'));
?>
<br/>
<?php
	echo $this->formSubmit($form->get('submit'));
	
?>
