<?php 
	$title = 'Datos';
	$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

	<ul class="list-group">
		<li class="list-group-item align-Items-center">
			<span>Nombre:</span><?php echo $post->getNombre();    ?></li>

			<li class="list-group-item align-Items-center">
			<span>Raza:</span><?php echo $post->getRaza();    ?>
		 </li>

			<li class="list-group-item align-Items-center">
			<span>Sexo:</span><?php echo $post->getSexo();    ?>
		 </li>

		 <li class="list-group-item align-Items-center">
			<span>Caracteristicas:</span><?php echo $post->getCaracteristicas();    ?>
		 </li>
</ul>

<div class="row">
    

<a href="<?php  echo $this->basePath('/'); ?>" class="btn btn-primary">SALIR</a>


</div>